on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    # - name: 🚀 Download Plugins
    #   uses: php-actions/composer@v6
      
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ secrets.USERNAME }}
        server: ${{ secrets.SERVER }}
        port: 65002
        local_path: ./wordpress/wp-content/themes/eara/
        remote_path: ./websites/nlcCpIU6b/public_html/wp-content/themes/
        # sftp_only: true
        password: ${{ secrets.PASSWORD }}
